### ISSUE TITLE
Keep ShellCheck action in Travis?

### ISSUE THREAD

**Issue by ecdye** [openhab/openhabian#991]
Do we really need to run the ShellCheck action in Travis if we already run it in GitHub Actions? Especially seeing as how we get the results from GitHub much faster? To make it apply to PRs all that would need to change in `shellcheck-action.yml` is:
``` yaml
on:
  push
```
to 
``` yaml
on: [push, pull_request]
```
See #990

**Comment by ecdye** [comment]
To quantify how fast it is, the latest check finished less than a minute after I pushed the commit.

**Comment by mstormi** [comment]
Mmh. I need to explicitly check for Github action results, don't I ?
I fear I'll quickly forget about shellchecking as soon as Travis does no longer enforce it.

**Comment by ecdye** [comment]
No, because it will be enforced as a check and if it fails the checks will report as failed. It should be apparent. Look at the checks tab on #990 to see what I mean.

**Comment by mstormi** [comment]
Ok, I don't mind then

**Comment by ecdye** [comment]
Even better, I believe that we can make it such that it only runs when bash files are changed by using the following: 
``` yaml
on:
  push:
    paths:
    - '**.bash'
    - '**.sh'
    - '!test.bash'
  pull_request:
    paths:
    - '**.bash'
    - '**.sh'
    - '!test.bash'
```
